# Generated by Django 2.2.3 on 2019-07-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='type',
            field=models.CharField(choices=[('t1', 'TYPE01'), ('t1', 'TYPE2')], default='t1', max_length=100),
        ),
    ]
