# Generated by Django 2.2.3 on 2019-07-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0002_auto_20190726_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='type',
        ),
    ]
